name: langbind
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.23.0
  - pandas
  - scipy
  - scikit-learn
  - tqdm
  - zlib
  - xz
  - readline
  - tk
  - sentencepiece
  - tensorboard
  - pip:
      - hf-trim
      - accelerate==0.20.3
      - aiohttp==3.10.6
      - attrs==24.2.0
      - av==13.0.0
      - beautifulsoup4==4.12.3
      - braceexpand==0.1.7
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - datasets==2.13.0
      - decord==0.6.0
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - evaluate==0.4.0
      - filelock==3.16.1
      - fsspec==2024.9.0
      - ftfy==6.1.1
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.25.1
      - importlib-metadata==8.5.0
      - iopath==0.1.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - markupsafe==2.1.5
      - nltk==3.9.1
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - open-clip-torch==2.26.1
      - opencv-python-headless
      - packaging==24.1
      - pandas==2.2.3
      - peft==0.4.0
      - pillow==10.4.0
      - protobuf==5.28.2
      - pytorchvideo==0.1.5
      - regex==2024.9.11
      - requests==2.32.3
      - safetensors==0.4.5
      - sentry-sdk==2.14.0
      - timm==1.0.9
      - torch
      - torchaudio
      - torchvision
      - transformers==4.30.2
      - wandb==0.18.1
      - webdataset==0.2.48
      - xxhash==3.5.0
      - yacs==0.1.8
      - zipp==3.20.2
